model_list:
  - model_name: starnet-router
    litellm_params:
      model: groq/openai/gpt-oss-20b
      api_key: os.environ/GROQ_API_KEY

  - model_name: starnet-router
    litellm_params:
      model: gemini/gemini-3.5-flash
      api_key: os.environ/GEMINI_API_KEY

  - model_name: starnet-router
    litellm_params:
      model: openrouter/openrouter/free
      api_key: os.environ/OPENROUTER_API_KEY

litellm_settings:
  drop_params: true
  callbacks: custom_callbacks.proxy_handler_instance

router_settings:
  routing_strategy: simple-shuffle
  enable_weighted_failover: true
  max_fallbacks: 3
  num_retries: 1
  allowed_fails: 1
  cooldown_time: 60
